import fs from 'fs/promises'
import path from 'path'
import { runFullScan } from './analysis'
import { loadBridgeConfig } from './bridgeConfig'
import { generateScanReport } from './scanReport'

export async function runScanCommand(repoPath: string, options: {
  format: 'json' | 'human' | 'agent'
  output?: string
  gates?: boolean
  quiet?: boolean
}) {
  const resolvedRepoPath = path.resolve(repoPath)
  const config = await loadBridgeConfig(resolvedRepoPath)
  const fullScan = await runFullScan(resolvedRepoPath, { skipConsoleUpload: false })

  if (!fullScan.scanReport) {
    throw new Error('Scan report was not generated by runFullScan().')
  }

  const report = fullScan.scanReport || await generateScanReport(
    resolvedRepoPath,
    config,
    fullScan,
    fullScan.techDebtScore,
    {
      patternFindings: fullScan.securityPatterns,
      oversizedFiles: fullScan.oversizedFiles
    }
  )

  if (options.gates && !report.gates.passed) {
    const fatalGates = report.gates.results.filter(result => !result.passed && result.severity === 'error')
    if (fatalGates.length > 0) {
      throw new Error(`Gates failed: ${fatalGates.map(g => g.name).join(', ')}`)
    }
  }

  let rendered = ''

  if (options.format === 'json') {
    rendered = JSON.stringify(report, null, 2)
  } else if (options.format === 'agent') {
    rendered = JSON.stringify({
      debt_score: report.techDebt.total,
      grade: report.techDebt.grade,
      critical: report.agentDigest.critical,
      top_actions: report.agentDigest.actions.slice(0, 5).map(item => ({
        title: item.title,
        impact: item.impact,
        effort: item.effort,
        command: item.command
      })),
      policies: report.agentDigest.policies,
      conventions: report.agentDigest.conventions,
      outdated_summary: report.agentDigest.outdated_summary
    }, null, 2)
  } else {
    rendered = [
      `Bridge Scan Report: ${report.repository.name}`,
      `Debt Score: ${report.techDebt.total} (${report.techDebt.grade}, ${report.techDebt.trend})`,
      `Critical Issues: ${report.agentDigest.critical.join(' | ')}`,
      `Top Actions:`,
      ...report.agentDigest.actions.slice(0, 5).map(item => `- [${item.dimension}] ${item.title} (impact ${item.impact}, effort ${item.effort})`),
      `Gates: ${report.gates.passed ? 'PASS' : 'FAIL'}`
    ].join('\n')
  }

  if (!options.quiet) {
    console.log(rendered)
  }

  if (options.output) {
    const outputPath = path.resolve(options.output)
    await fs.mkdir(path.dirname(outputPath), { recursive: true })
    await fs.writeFile(outputPath, rendered + '\n', 'utf-8')
  }

  return report
}
